name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@master
        with:
          root_file: resume.tex
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
      - uses: actions/upload-artifact@v2
        with:
          name: resume.pdf
          path: resume.pdf  
